package main

import "os"
import "regexp"

func main() {

r := regexp.MustCompile("\\x1b[[][?0123456789]*;?[?0123456789]*[ABCDEFGHJKRSTfminsulhp]")


os.Stdout.WriteString(r.ReplaceAllString("\x1b[2K\x1b[4G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2K\x1b[4G\x1b[90m[4/4]\x1b[39m Building fresh packages...\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2K\x1b[1G      \n\x1b[2K\x1b[1G      \n\x1b[2K\x1b[1G      \n\x1b[2K\x1b[1G      \n", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B\x1b[1G\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B\x1b[1G\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B\x1b[1G\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B\x1b[1G\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K\x1b[1G\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G\x1b[2A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B\x1b[1G\x1b[2A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[1A\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G\x1b[2B\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A\x1b[0K\x1b[1G\x1b[3B\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[1B\x1b[1G\x1b[2A\x1b[0K\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2B\x1b[1G\x1b[3A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[0K\x1b[1G\x1b[3B\x1b[1G\x1b[4A\x1b[0K\x1b[1G\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A\x1b[2K\x1b[4B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[3A\x1b[2K\x1b[3B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2A\x1b[2K\x1b[2B", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1A\x1b[2K\x1b[1B\x1b[2K", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[1G\x1b[4A", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2K\x1b[1G\x1b[32m      success\x1b[39m Saved lockfile.\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("\x1b[2K\x1b[1G      Done in 43.45s.\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("    \n", ""))
os.Stdout.WriteString(r.ReplaceAllString("    - Installing bower components :\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mnot-cached   \x1b[39m https://github.com/jasperla/prism-langs.git#*\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mresolve      \x1b[39m https://github.com/jasperla/prism-langs.git#*\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mnot-cached   \x1b[39m https://github.com/tolmark12/shadow-icons-js.git#*\n      bower \x1b[36mresolve      \x1b[39m", ""))
os.Stdout.WriteString(r.ReplaceAllString(" https://github.com/tolmark12/shadow-icons-js.git#*\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mnot-cached   \x1b[39m https://github.com/nanobox-io/top-nav.git#*\n      bower \x1b[36mresolve      \x1b[39m https://github.com/nanobox-io/top-nav.git#*\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mnot-cached   \x1b[39m https://github.com/bendc/sprint.git#*\n      bower \x1b[36mresolve      \x1b[39m https://github.com/bendc/sprint.git#*\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mnot-cached   \x1b[39m https://github.com/mroderick/PubSubJS.git#~1.5.0\n      bower \x1b[36mresolve      \x1b[39m https://github.com/mroderick/PubSubJS.git#~1.5.0\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mnot-cached   \x1b[39m https://github.com/julianshapiro/velocity.git#~1.2.2\n      bower \x1b[36mresolve      \x1b[39m https://github.com/julianshapiro/velocity.git#~1.2.2\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mnot-cached   \x1b[39m https://github.com/browserstate/history.js.git#~1.8.0\n      bower \x1b[36mresolve      \x1b[39m https://github.com/browserstate/history.js.git#~1.8.0\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mnot-cached   \x1b[39m https://github.com/LeaVerou/prism.git#*\n      bower \x1b[36mresolve      \x1b[39m https://github.com/LeaVerou/prism.git#*\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mnot-cached   \x1b[39m https://github.com/jozefizso/bower-jquery-easing.git#~1.3.0\n      bower \x1b[36mresolve      \x1b[39m https://github.com/jozefizso/bower-jquery-easing.git#~1.3.0\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mnot-cached   \x1b[39m https://github.com/jquery/jquery-dist.git#~2.1.1\n      bower \x1b[36mresolve      \x1b[39m https://github.com/jquery/jquery-dist.git#~2.1.1\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mnot-cached   \x1b[39m https://github.com/visionmedia/jade.git#~1.6.0\n      bower \x1b[36mresolve      \x1b[39m https://github.com/visionmedia/jade.git#~1.6.0\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mdownload     \x1b[39m https://github.com/jasperla/prism-langs/archive/master.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mdownload     \x1b[39m https://git", ""))
os.Stdout.WriteString(r.ReplaceAllString("hub.com/tolmark12/shadow-icons-js/archive/master.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mdownload     \x1b[39m https://github.com/nanobox-io/top-nav/archive/master.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mdownload     \x1b[39m https://github.com/bendc/sprint/archive/master.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mdownload     \x1b[39m https://github.com/mroderick/PubSubJS/archive/v1.5.4.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mdownload     \x1b[39m https://github.com/browserstate/history.js/archive/1.8.0.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mdownload     \x1b[39m https://github.com/julianshapiro/velocity/archive/1.2.3.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mdownload     \x1b[39m https://github.com/LeaVerou/prism/archive/v1.6.0.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mextract      \x1b[39m prism-langs#* archive.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mextract      \x1b[39m top-nav#* archive.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mdownload     \x1b[39m https://github.com/jozefizso/bower-jquery-easing/archive/v1.3.1.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mresolved     \x1b[39m https://github.com/jasperla/prism-langs.git#5d167d6cff\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mresolved     \x1b[39m https://github.com/nanobox-io/top-nav.git#e6426efc7c\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mdownload     \x1b[39m https://github.com/jquery/jquery-dist/archive/2.1.4.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mextract      \x1b[39m sprint.js#* archive.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mresolved     \x1b[39m https://github.com/bendc/sprint.git#a220796dc6\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mextract      \x1b[39m pubsub-js#~1.5.0 archive.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mextract      \x1b[39m shadow-icons#* archive.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[33minvalid-meta \x1b[39m for:/tmp/gonano/bower/9f914793e18982206e2af59431c77020-563-lIIGsC/bower.json\n      bower \x1b[33minvalid-meta \x1b[39m The \"nam", ""))
os.Stdout.WriteString(r.ReplaceAllString("e\" is recommended to be lowercase, can conta", ""))
os.Stdout.WriteString(r.ReplaceAllString("in digits, dots, dashes\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[33mmismatch     \x1b[39m Version declared in the json (1.5.3) is", ""))
os.Stdout.WriteString(r.ReplaceAllString(" different than the resolved one (1.5.4)\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mresolved     \x1b[39m https://github.com/mroderick/PubSubJS.git#1.5.4\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mresolved     \x1b[39m https://github.com/tolmark12/shadow-icons-js.git#67a8409e15\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mextract      \x1b[39m jquery.easing#~1.3.0 archive.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mresolved     \x1b[39m https://github.com/jozefizso/bower-jquery-easing.git#1.3.1\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mnot-cached   \x1b[39m https://github.com/jquery/jquery-dist.git#>= 1.2.1\n      bower \x1b[36mresolve      \x1b[39m https://github.com/jquery/jquery-dist.git#>= 1.2.1\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mdownload     \x1b[39m https://github.com/jquery/jquery-dist/archive/3.1.1.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mdownload     \x1b[39m https://github.com/visionmedia/jade/archive/1.6.0.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mextract      \x1b[39m velocity#~1.2.2 archive.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[33minvalid-meta \x1b[39m for:/tmp/gonano/bower/ac1a453d0cdc1f19d9479ccfaa8b082c-563-ESIKnq/bower.json\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[33minvalid-meta \x1b[39m The \"main\" field has to contain only 1 file per filetype; found multiple .js files: [\"./velocity.js\",\"./velocity.ui.js\"]\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mresolved     \x1b[39m https://github.com/julianshapiro/velocity.git#1.2.3\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mnot-cached   \x1b[39m https://github.com/jquery/jquery-dist.git#*\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mresolve      \x1b[39m https://github.com/jquery/jquery-dist.git#*\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mdownload     \x1b[39m https://github.com/jquery/jquery-dist/archive/3.1.1.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mextract      \x1b[39m jade#~1.6.0 archive.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mextract      \x1b[39m jquery#~2.1.1 archive.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mresolved     \x1b[39m https://github.com/visionmedia/jade.git#1.6.0\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mresolved     \x1b[39m https://github.com/jquery/jquery-dist.git#2.1.4\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mextract      \x1b[39m jquery#* archive.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mresolved     \x1b[39m https://github.com/jquery/jquery-dist.git#3.1.1\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mextract      \x1b[39m jquery#>= 1.2.1 archive.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mextract      \x1b[39m history.js#~1.8.0 archive.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mresolved     \x1b[39m https://github.com/jquery/jquery-dist.git#3.1.1\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mresolved     \x1b[39m https://github.com/browserstate/history.js.git#1.8.0\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mextract      \x1b[39m prism#* archive.tar.gz\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36mresolved     \x1b[39m https://github.com/LeaVerou/prism.git#1.6.0\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36minstall      \x1b[39m prism-langs#5d167d6cff\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36minstall      \x1b[39m top-nav#e6426efc7c\n      bower \x1b[36minstall      \x1b[39m sprint.js#a220796dc6\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36minstall      \x1b[39m pubsub-js#1.5.4\n      bower \x1b[36minstall      \x1b[39m shadow-icons#67a8409e15\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36minstall      \x1b[39m jquery.easing#1.3.1\n      bower \x1b[36minstall      \x1b[39m velocity#1.2.3\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36minstall      \x1b[39m jade#1.6.0\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36minstall      \x1b[39m jquery#2.1.4\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      bower \x1b[36minstall      \x1b[39m history.js#1.8.0\n      bower \x1b[36minstall      \x1b[39m prism#1.6.0\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      \n      prism-langs#5d167d6cff bower_components/prism-langs\n      \n      top-nav#e6426efc7c bower_components/top-nav\n      \n      sprint.js#a220796dc6 bower_components/sprint.js\n      \n      pubsub-js#1.5.4 bower_components/pubsub-js\n      \n      shadow-icons#67a8409e15 bower_components/shadow-icons\n      \n      jquery.easing#1.3.1 bower_components/jquery.easing\n      └── jquery#2.1.4\n      \n      velocity#1.2.3 bower_components/velocity\n      └── jquery#2.1.4\n      \n      jade#1.6.0 bower_components/jade\n      \n      jquery#2.1.4 bower_components/jquery\n      \n      history.js#1.8.0 bower_components/history.js\n      \n      prism#1.6.0 bower_components/prism\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("    \n", ""))
os.Stdout.WriteString(r.ReplaceAllString("  Packaging build :\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("    - Stashing build environment...\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("    - Stashing home into cache...\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("    - Stashing pkg cache...\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("    - Uninstalling packages :\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("      no such installed package nodejs-4\n      no such installed package python-2.7\n      no packages to delete\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("    \n", ""))
os.Stdout.WriteString(r.ReplaceAllString("    - Removing orphaned packages...\n", ""))
os.Stdout.WriteString(r.ReplaceAllString("    - Stashing deploy environment...\n", ""))
	
}